version: '3.8'

services:
  asset_db:
    image: postgres:15-alpine
    container_name: asset_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asset_db
    ports:
      - "5432:5432"
    volumes:
      - asset_db_data:/var/lib/postgresql/data

  asset-service:
    build: ./services/asset-service
    container_name: asset-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://asset_db:5432/asset_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_ENDPOINT=${R2_ENDPOINT}
    depends_on:
      - asset_db
    restart: always

volumes:
  asset_db_data:
