version: '3.8'

services:
  asset_db:
    image: postgres:15-alpine
    container_name: asset_service_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - asset_db_data:/var/lib/postgresql/data

  asset-service:
    build: ./services/asset-service
    container_name: asset-service
    ports:
      - "${APP_PORT}:${APP_INTERNAL_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
    volumes:
      - ${APPDATA}/gcloud:/root/.config/gcloud # Mount gcloud credentials for ADC
    depends_on:
      - asset_db
    restart: always

volumes:
  asset_db_data:
